# Generated by Django 5.0.6 on 2024-06-08 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolineas',
            fields=[
                ('id_aerolinea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aerolinea', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuertos',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_aeropuerto', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.aerolineas')),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.aeropuertos')),
                ('id_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcrud.movimientos')),
            ],
        ),
    ]
